# Generated by Django 3.0.7 on 2020-06-07 14:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200606_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview',
            field=ckeditor.fields.RichTextField(default='Default Preview Here'),
            preserve_default=False,
        ),
    ]
