# Generated by Django 3.0.7 on 2020-06-12 00:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='article_image',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
