# Generated by Django 3.0.7 on 2020-06-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topics',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
