# Generated by Django 3.0.7 on 2020-06-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200620_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(to='blog.Topic'),
        ),
    ]
