# Generated by Django 3.0.7 on 2020-06-20 22:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200620_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_image',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
