# Generated by Django 3.0.7 on 2020-06-20 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_topic_topic_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topic_image',
        ),
    ]
