# Generated by Django 3.0.7 on 2020-06-25 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200621_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='preview',
        ),
    ]
